[package]
authors = ["Dragan Rakita <dragan0rakita@gmail.com>"]
description = "REVM - Rust Ethereum Virtual Machine"
edition = "2021"
keywords = ["no_std", "ethereum", "evm", "revm"]
license = "MIT"
name = "revm"
repository = "https://github.com/bluealloy/revm"
version = "3.0.0"
readme = "../../README.md"

[dependencies]
revm-precompile = { path = "../precompile", version = "2.0.0", default-features = false }
revm-interpreter = { path = "../interpreter", version = "1.0.0", default-features = false }

auto_impl = { version = "1.1", default-features = false }

# Optional
serde = { version = "1.0", features = ["derive", "rc"], optional = true }
serde_json = { version = "1.0", features = ["preserve_order"], optional = true }

# ethersdb
tokio = { version = "1.26", features = [
    "rt-multi-thread",
    "macros",
], optional = true }
ethers-providers = { version = "1.0.2", optional = true }
ethers-core = { version = "1.0.2", optional = true }
futures = { version = "0.3.27", optional = true }


[dev-dependencies]
hex-literal = "0.3"

[features]
default = ["std", "secp256k1"]
dev = [
    "memory_limit",
    "optional_balance_check",
    "optional_block_gas_limit",
    "optional_eip3607",
    "optional_gas_refund",
    "optional_no_base_fee",
]
secp256k1 = ["revm-precompile/secp256k1"]
memory_limit = ["revm-interpreter/memory_limit"]
no_gas_measuring = ["revm-interpreter/no_gas_measuring"]
optional_balance_check = ["revm-interpreter/optional_balance_check"]
optional_block_gas_limit = ["revm-interpreter/optional_block_gas_limit"]
optional_eip3607 = ["revm-interpreter/optional_eip3607"]
optional_gas_refund = ["revm-interpreter/optional_gas_refund"]
optional_no_base_fee = ["revm-interpreter/optional_no_base_fee"]
std = ["revm-interpreter/std"]
ethersdb = ["tokio", "futures", "ethers-providers", "ethers-core"]
serde = ["dep:serde","dep:serde_json", "revm-interpreter/serde"]
# deprecated feature
web3db = []
with-serde = []
